version: '3'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: pgbouncer-test
      POSTGRES_PASSWORD: 3110c3854984452d2507939280167b8c4dd8c0bb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgbouncer:
    build:
      context: .
    restart: always
    environment:
      POSTGRES_DB: pgbouncer-test
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3110c3854984452d2507939280167b8c4dd8c0bb
    ports:
      - 9432:5432
    depends_on:
      postgres:
        condition: service_healthy
